# Generated by Django 2.2 on 2019-04-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Tag text (must be lowercase)', max_length=100, unique=True)),
                ('tasks', models.ManyToManyField(related_name='tags', to='core.Task')),
            ],
        ),
    ]
